version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-backend
    container_name: nestjs-backend
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - app-network
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: ${MONGODB_URL}
    volumes:
      - .:/nest

  mongodb:
    image: mongo
    container_name: nestjs-mongodb
    restart: always
    networks:
      - app-network
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./server:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  minio:
    image: minio/minio
    container_name: minio-server
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    # environment:
    #     MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
    #     MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data
    env_file: .env
    restart: always

networks: 
  app-network:
    driver: bridge
